baseURL = "https://magc0da.github.io/"
languageCode = "zh-cn"
title = "Solve et Coagula"
theme = "PaperMod"

[params]
math = true
defaultTheme = "dark" # 默认开启深色模式
    disableThemeToggle = true # 禁用切换按钮，保持神秘的深夜氛围   

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 10

[[menu.main]]
    name = "Traveling"
    url = "/traveling/"
    weight = 20

[[menu.main]]
    name = "Photos"
    url = "/photos/"
    weight = 30

[[menu.main]]
    name = "Expository Notes"
    url = "/expository notes/"
    weight = 40

[[menu.main]]
    name = "神棍诸事"
    url = "/taoism/"
    weight = 50    

[params.profileMode]
    enabled = true
    title = " Sciens Arcana "  # 或者用拉丁文
    subtitle = " Coagula in Condensatum | Solve per Prisma  <br><br> 数论爱好者, 职业神棍, 目前暂时在学算术几何 "
    imageUrl = "/images/avatar.jpg" # 放一张神秘主义符号图片
    imageWidth = 150
    imageHeight = 120
    [[params.profileMode.buttons]]
        name = "Fictions"
        url = "/fiction"
    